### ISSUE TITLE
thresholds with mode subscription

### ISSUE THREAD

**Issue by MBoening** [nbuchwitz/check_pve#10]
If you add a warning threshold of 60 days (-w60) and a critical threshold of 30 days (-c30) you'll get the following error:
`check_pve.py: error: Critical value must be greater than warning value`

**Comment by nbuchwitz** [comment]
Thanks for reporting. Should be fixed in current GIT master

**Comment by MBoening** [comment]
Hi,
The subscription check works now, but I get errors on "cpu" / "memory" and "io_wait"
`check_pve.py: error: Critical value must be lower than warning value`

**Comment by nbuchwitz** [comment]
Could you test again?

**Comment by MBoening** [comment]
It works, thanks.
