### ISSUE TITLE
Warning/Critical Thresholds for Mode 'vm' 

### ISSUE THREAD

**Issue by MBoening** [nbuchwitz/check_pve#11]
Hi,
I just noticed that a VM is running high on memory but the check says it's ok.

check_pve.py --vmid X -e X -k -m vm -n X -p X -u X -w 50 -c 60 
**OK** - VM 'X' on node 'X' is running|cpu=3.87%;50.0;60.0 memory=**94.5%**;_**50.0;60.0**_

Might it be possible to differentiate between CPU and memory warning levels?

**Comment by nbuchwitz** [comment]
This is indeed a bug, thanks again for reporting. I fixed the threshold check in the current GIT master.

**Comment by nbuchwitz** [comment]
I'm not certain how to differentiate (in a clean way) between threshold for memory and CPU.

**Comment by MBoening** [comment]
It works
`check_pve.py --vmid X-e X -k -m X -n X -p X u X -w 50 -c 60`
`CRITICAL - VM 'X' on node 'X' is running|cpu=3.43%;50.0;60.0 memory=94.94%;50.0;60.0`

**Comment by nbuchwitz** [comment]
Perfect. I created a new issue (#12) for keeping track of the CPU threshold feature and will close this.
