### ISSUE TITLE
UNKNOWN - Could not connect to PVE API: Certificate validation failed

### ISSUE THREAD

**Issue by roadrunnerjb** [nbuchwitz/check_pve#15]
Hi,
I just set up my first two proxmox nodes in a cluster and want to monitor health.

When I do the first tests I get the error above. 

/check_pve.py -u monitoring -p ------- -e target -m version  -V 5.0.0
UNKNOWN - Could not connect to PVE API: Certificate validation failed

passwordless ssh connect between the two nodes is possible, both have the same software level.

root@xen5:/# ssh xen4 uname -a
Linux xen4 4.15.18-18-pve #1 SMP PVE 4.15.18-44 (Wed, 03 Jul 2019 11:19:13 +0200) x86_64 GNU/
Any hint on hotwo proceed ?

Regards
Joachim

**Comment by pantokrr** [comment]
This is most likely because you have a self-signed certificate on your PVE instance.  Adding option "-k" or "--insecure" will disable certificate validation.

**Comment by roadrunnerjb** [comment]
thx for your quick reply works now
