### ISSUE TITLE
Setting of pve_unit useless?

### ISSUE THREAD

**Issue by wopfel** [nbuchwitz/check_pve#19]
Hi, in the `service.conf` sample file there are some lines

```
pve_unit = "%"
```

But there's no reference to `pve_unit` in the `command.conf` file. Should this be related to the `-M` switch?

Kind regards,
Bernd

**Comment by nbuchwitz** [comment]
Good catch! This was used in an older release, but is not relevant anymore. There is the argument `-M` for changing the unit to megabyte instead of percent.

**Comment by wopfel** [comment]
All right. So would you accept another PR? I'd just delete the pve_unit lines from the config file...

**Comment by nbuchwitz** [comment]
That would be more than welcome :-)
