### ISSUE TITLE
Adding VM check to sample files?

### ISSUE THREAD

**Issue by wopfel** [nbuchwitz/check_pve#20]
Thanks for supplying the Icinga2 conf files. Unfortunately, I've spotted your files just a few moments after typing the config by myself... 😉

In my config, there's a (very rudimentary) VM check. Maybe adding that part to your conf file would help other people?

```
object Host "..." {
  import "proxmox-host"

  vars.virtual_machines["icinga-alt"] = {
  }
  ...
}

apply Service "pve-vm " for (vm => config in host.vars.virtual_machines) {
  import "pve-service"

  vars.pve_mode = "vm"
  vars.pve_resource_name = vm

  assign where host.vars.pve_host
}
```

Kind regards,
Bernd

**Comment by nbuchwitz** [comment]
Looks good to me. Would you mind to put this into a PR?
