### ISSUE TITLE
README

### ISSUE THREAD

**Issue by ftrojahn** [nbuchwitz/check_pve#28]
Hi Nicolai,

* small typo in README (missing "r") 
     pveum user token add monitoing@pve monitoring

* is "Sys.Modify" really needed ... if yes, why?
     pveum roleadd Monitoring
     pveum rolemod Monitoring --privs Sys.Modify,VM.Monitor,Sys.Audit,Datastore.Audit,VM.Audit

Thanx!

**Comment by nbuchwitz** [comment]
Thanks! I fixed it and it will be part of the next release. 

The `Sys.Modify` permission seems to be unnecessary, so I removed it from the README
