### ISSUE TITLE
VM and LXC status check should also include disk information.

### ISSUE THREAD

**Issue by hamapj** [nbuchwitz/check_pve#45]
I would like to monitor disk usage for vm and lxc. I did not find a way to monitor disk usage of a vm/lxc with the current implementation. Please guide me in the right direction if I simply missed that functionality while reading through documentation/code.

My first thought was to implement this by adding additional performance data for the disk to check_vm_status(). I am unsure if this should be guarded by an additional parameter, as it would extend the monitoring for current users and might lead to unexpected check results.

Let me know what you think about this. I would gladly create a PR.

**Comment by hamapj** [comment]
I added additional functionality for this in [this](https://github.com/nbuchwitz/check_pve/pull/46) PR.

**Comment by nbuchwitz** [comment]
Should be fixed with #47
