### ISSUE TITLE
[BUG] Subscription informations are not available

### ISSUE THREAD

**Issue by devaux** [nbuchwitz/check_pve#55]
**Describe the bug**
On the PVE there is a current "Proxmox VE Basic Subscription 1 CPU/year" license installed.
When reading out the subscription infos i only get "**OK -** ".

**To Reproduce**
used command:
check_pve.py -u <API_USER> -p <API_PASSWORD> -e <API_ENDPOINT> -m subscription -n node1 -w 50 -c 10

**Expected behavior**
Should get the license name and license period.

**Environment (please complete the following information):**
- Ubuntu 24.04
- Python 3.12.3
- PVE 8.2.2

**Comment by nbuchwitz** [comment]
This *should* be fixed in current master with https://github.com/nbuchwitz/check_pve/commit/86805df4be170bd47b64df5026426cb2eb83feb2

?

**Comment by devaux** [comment]
Thanks! This fixes the issue.

`OK - Proxmox VE Basic Subscription 1 CPU/year is valid until 2025-04-26
`
