### ISSUE TITLE
Error thrown by python: type object 'datetime.datetime' has no attribute 'UTC'

### ISSUE THREAD

**Issue by wopfel** [nbuchwitz/check_pve#57]
Hi,
I just downloaded your current version of the script since I've spotted the backup check. Very nice! 

When running on my system, I get an error:

```
root@icinga ~ # /usr/local/bin/check_pve-new-github.py -e xxx -m backup -n xxx -p xxx -u monitoring@pve -c 9186400
Traceback (most recent call last):
  File "/usr/local/bin/check_pve-new-github.py", line 1110, in <module>
    pve.check()
  File "/usr/local/bin/check_pve-new-github.py", line 875, in check
    self.check_vzdump_backup(self.options.name)
  File "/usr/local/bin/check_pve-new-github.py", line 680, in check_vzdump_backup
    now = datetime.now(datetime.UTC).timestamp()
AttributeError: type object 'datetime.datetime' has no attribute 'UTC'
```

Changing line 680 to:
`            now = datetime.utcnow().timestamp()`

the script runs without error. For example:
```
WARNING - 21 backup tasks successful, 0 backup tasks failed within the last 9186400.0s
There are guests not covered by any backup schedule: 544 547 552 549 117 521 548 545 551 550
```

Maybe it's specific to my very old Ubuntu installation. But if anyone else faces this error, I'm happy to share my solution.

My system version:
```
root@icinga ~ # lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

Regards,
Bernd

**Comment by nbuchwitz** [comment]
Which Python version do you use?

**Comment by dagobert** [comment]
I ran into the same problem. I tried your fix and it works!

**Comment by wopfel** [comment]
> Which Python version do you use? 

Python 3.8.10

> `datetime.utcnow()` is deprecated and will be removed in future Python versions. Could you please try if the following works for your setup? #58

Thanks for your comment. I favor your changes in #58 since there's no sense implementing deprecated code.
